In [1]:
import pandas as pd

In [2]:
# Load your dataset
data = pd.read_csv('fooddelivery_updated_sentiment.csv')

In [3]:
data.head()

,content,score,thumbsUpCount,Apps,sentiment,afinn_score,vader_neg,vader_neu,vader_pos,vader_compound,word_count
0,deleted dont like being called out for not tip...,1,0,DoorDash,-1,-1.0,0.102,0.814,0.084,0.1002,31
1,while abbreviation msg fitters outed gudsmoked...,5,0,DoorDash,1,7.0,0.000,0.561,0.439,0.9100,20
2,They come through especially when your running...,5,0,DoorDash,1,-1.0,0.000,0.841,0.159,0.2235,11
3,I love DoorDash,5,0,DoorDash,1,3.0,0.000,0.323,0.677,0.6369,3
4,THEY STEAL MONEY! I used to order often and of...,1,0,DoorDash,-1,-10.0,0.135,0.851,0.014,-0.9148,96

In [4]:
len(data)

1694938

In [5]:
#data = data[data['sentiment'] != -1]

In [6]:
#data = data[data['sentiment'] != 0]

In [7]:
len(data)

1694938

In [15]:
# Count the total number of 'NaN' values in the DataFrame
total_nan_count = data.isna().sum().sum()

In [16]:
# Display the total number of 'NaN' values
print("Total number of NaN values:", total_nan_count)

Total number of NaN values: 357

In [17]:
# Check which columns contain NaN values
columns_with_nan = data.columns[data.isna().any()].tolist()

# Display the columns with NaN values
print("Columns with NaN values:", columns_with_nan)

Columns with NaN values: ['content']

In [19]:
data = data[pd.notnull(data['content'])]

In [20]:
# Count the total number of 'NaN' values in the DataFrame
total_nan_count = data.isna().sum().sum()

In [21]:
# Display the total number of 'NaN' values
print("Total number of NaN values:", total_nan_count)

Total number of NaN values: 0

In [22]:
# Define a list of ease of use-related keywords
ease_of_use_keywords = [
    'user-friendly', 'intuitive', 'simple', 'straightforward', 'convenient',
    'effortless', 'easy to use', 'user-friendly interface', 'user-friendly design',
    'smooth', 'efficiency', 'convenient', 'intuitive design', 'user-friendly app',
    'user-friendly interface', 'user-friendly experience', 'easy navigation',
    'user-friendly features', 'user-friendly design', 'easy access',
    'straightforward usability', 'user satisfaction', 'user experience', 'convenient functionality',
    'intuitive usability', 'smooth operation', 'efficient design', 'straightforward interaction',
    'convenient layout', 'effortless navigation', 'user-friendly layout', 'intuitive operation',
    'simple usage', 'convenient features', 'straightforward design', 'effortless experience',
    'user-friendly functionalities', 'convenient operation', 'easy handling', 'efficiency features',
    'intuitive user interface', 'simple design', 'user-friendly functions', 'straightforward usability',
    'convenient interface', 'effortless accessibility', 'user satisfaction features',
    'user-centric', 'accessible', 'streamlined', 'hassle-free', 'simplified', 'ergonomic',
    'responsive', 'painless', 'effortless usage', 'friendly interface', 'user-driven', 'clear',
    'user-focused', 'well-designed', 'easy-to-navigate',
    'practical', 'helpful', 'user-oriented', 'self-explanatory', 'quick access', 'uncomplicated',
    'trouble-free', 'conducive', 'effective', 'pleasant', 'efficient interface',
    'straightforward features', 'comfortable', 'logically organized', 'intuitive functionality',
    'user-first', 'user-savvy', 'time-saving', 'highly usable', 'user-responsive',
    'no-brainer', 'intuitive operation', 'user-empowered', 'easygoing', 'accessible design', 'thoughtful design', 'user-engaging', 'user-helpful', 'smart design',
    'hassle-free usage', 'welcoming', 'obvious', 'intuitively organized', 'ergonomic layout',
    'pleasing', 'easily navigable', 'user-approved', 'user-driven features'
]

In [23]:
# Define a list of intention to use-related keywords
intention_to_use_keywords = [
    'plan to use', 'intend to use', 'will use', 'want to use', 'intention to use',
    'consider using', 'wish to use', 'have to use', 'interested in using', 'going to use',
    'future use', 'potential use', 'looking to use', 'aim to use', 'will continue using',
    'use it more', 'use it again', 'used regularly', 'using it frequently', 'intend to keep using',
    'future intention', 'future adoption', 'desire to use', 'interest in usage', 'aim to continue using',
    'planning to adopt', 'future utilization', 'anticipate using', 'willing to use', 'will likely use',
    'intend to utilize', 'consider future use', 'intent to adopt', 'intention to continue using',
    'future application', 'intent to engage', 'aspiration to use', 'goal to use', 'expectation to utilize',
    'purpose to use', 'prospect to use', 'future involvement', 'inclination to use', 'inclined to utilize',
    'consideration to engage', 'intention to utilize', 'likelihood of usage', 'likelihood of adoption',
    'intention to apply', 'prospect to adopt', 'consider future adoption', 'future intention to use',
    'plan to continue using', 'future utilization intention', 'intention to apply it', 'prospective use',
    'intending to use', 'preference for usage', 'wants to continue using', 'aspirations to use',
    'desires to use', 'future usage plan', 'considering using in the future', 'aims to use it more',
    'potential to keep using', 'intent to continue using', 'inclination to utilize more',
    'potential to use it again', 'intending to use it frequently', 'prospects to use regularly',
    'future intention to keep using', 'planning to use it more', 'will likely use it again',
    'desiring to use it frequently', 'future intentions to keep using', 'future aspirations to use',
    'intentions to continue using', 'expecting to use it again', 'intending to keep using regularly',
    'future intent to use frequently', 'prospects to keep using it again', 'intending to use it continually',
    'potential to use it repeatedly', 'intention to apply it regularly', 'prospective usage',
    'intending to use it repeatedly', 'future usage planning', 'considering repeated use',
    'wants to use it regularly', 'aspires to use it repeatedly', 'desires to use it continually',
    'future usage intent', 'intentions to apply it regularly', 'considering it for regular use',
    'aims to use it repeatedly', 'potential to use it continually', 'intent to apply it repeatedly',
    'anticipations for regular usage', 'intentions for continued use', 'intent to engage regularly',
    'aspires to keep using']

In [24]:
# Define a list of usefulness-related keywords
usefulness_keywords = [ 'useful', 'helpful', 'beneficial', 'valuable', 'effective',
    'productive', 'informative', 'practical', 'convenient', 'efficient',
    'worthwhile', 'functional', 'handy', 'advantageous', 'essential',
    'effective tool', 'useful features', 'valuable information', 'convenient solution', 'helpful resource',
    'practical functionality', 'efficient features', 'beneficial features', 'valuable features', 'essential features',
    'convenient features', 'practical features', 'efficient tool', 'productive features', 'effective resource',
    'informative features', 'functional tool', 'handy features', 'advantageous tool', 'essential resource',
    'valuable solution', 'effective solution', 'helpful solution', 'beneficial tool', 'practical resource', 'efficient solution', 'informative tool', 'productive tool', 'valuable resource', 'useful solution', 'convenient resource',
    'effective functionality', 'user value', 'utility', 'usefulness factor', 'effectiveness', 'practicality', 'handiness', 'relevance',
    'efficacy', 'useful resource', 'valuable features', 'valuable tool', 'convenience', 'functionality', 'useful information',
    'beneficial functionality', 'convenient tool', 'valuable solution', 'efficient information', 'informative solution',
    'functional features', 'helpful features', 'worthwhile information', 'practical information', 'handy information', 'advantageous information',
    'essential information', 'efficient solution', 'productive solution', 'functional solution', 'informative features',
    'valuable functionality', 'useful functionalities', 'convenient features', 'helpful functionalities', 'useful functions',
    'useful addition', 'beneficial aspect', 'valuable attribute', 'effective attribute', 'helpful feature', 'functional qualities',
    'informative resources', 'convenient solutions', 'efficient characteristic', 'productive advantages',
    'essential elements', 'user-friendly utilities', 'user satisfaction', 'user experience enhancement', 'convenient enhancements', 'functional enhancements', 'useful enhancements', 'helpful utilities'

    ]

In [25]:
# Function to check if any keyword is present in the text
def has_keyword(text, keywords):
    for keyword in keywords:
        if keyword in text:
            return 1
    return 0

In [26]:
# Create new columns for Ease of Use, Intention to Use, and Usefulness
data['Ease_of_Use'] = data['content'].apply(lambda x: has_keyword(x, ease_of_use_keywords))
data['Intention_to_Use'] = data['content'].apply(lambda x: has_keyword(x, intention_to_use_keywords))
data['Usefulness'] = data['content'].apply(lambda x: has_keyword(x, usefulness_keywords))

<ipython-input-26-f4187cac3311>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Ease_of_Use'] = data['content'].apply(lambda x: has_keyword(x, ease_of_use_keywords))
<ipython-input-26-f4187cac3311>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Intention_to_Use'] = data['content'].apply(lambda x: has_keyword(x, intention_to_use_keywords))
<ipython-input-26-f4187cac3311>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Usefulness'] = data['content'].apply(lambda x: has_keyword(x, usefulness_keywords))

In [27]:
# Replace 1 in 'Ease_of_Use_Indicator' with -1 when 'sentiment' is -1
data['Ease_of_Use'] = data.apply(lambda row: -1 if row['sentiment'] == -1 else row['Ease_of_Use'], axis=1)

<ipython-input-27-374b0d76ad46>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Ease_of_Use'] = data.apply(lambda row: -1 if row['sentiment'] == -1 else row['Ease_of_Use'], axis=1)

In [28]:
data['Intention_to_Use'] = data.apply(lambda row: -1 if row['sentiment'] == -1 else row['Intention_to_Use'], axis=1)

<ipython-input-28-67a34650dc14>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Intention_to_Use'] = data.apply(lambda row: -1 if row['sentiment'] == -1 else row['Intention_to_Use'], axis=1)

In [29]:
data['Usefulness'] = data.apply(lambda row: -1 if row['sentiment'] == -1 else row['Usefulness'], axis=1)

<ipython-input-29-8f6e3bb73e22>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Usefulness'] = data.apply(lambda row: -1 if row['sentiment'] == -1 else row['Usefulness'], axis=1)

In [30]:
data.head()

,content,score,thumbsUpCount,Apps,sentiment,afinn_score,vader_neg,vader_neu,vader_pos,vader_compound,word_count,Ease_of_Use,Intention_to_Use,Usefulness
0,deleted dont like being called out for not tip...,1,0,DoorDash,-1,-1.0,0.102,0.814,0.084,0.1002,31,-1,-1,-1
1,while abbreviation msg fitters outed gudsmoked...,5,0,DoorDash,1,7.0,0.000,0.561,0.439,0.9100,20,0,0,0
2,They come through especially when your running...,5,0,DoorDash,1,-1.0,0.000,0.841,0.159,0.2235,11,0,0,0
3,I love DoorDash,5,0,DoorDash,1,3.0,0.000,0.323,0.677,0.6369,3,0,0,0
4,THEY STEAL MONEY! I used to order often and of...,1,0,DoorDash,-1,-10.0,0.135,0.851,0.014,-0.9148,96,-1,-1,-1

In [31]:
print(data["Ease_of_Use"].value_counts())

 0    1121754
-1     467599
 1     105228
Name: Ease_of_Use, dtype: int64

In [32]:
print(data["Intention_to_Use"].value_counts())

 0    1225472
-1     467599
 1       1510
Name: Intention_to_Use, dtype: int64

In [33]:
print(data["Usefulness"].value_counts())

 0    1148448
-1     467599
 1      78534
Name: Usefulness, dtype: int64

In [34]:
# Calculate the total count of '1' values for each column
ease_of_use_count = data['Ease_of_Use'].sum()
intention_to_use_count = data['Intention_to_Use'].sum()
usefulness_count = data['Usefulness'].sum()

In [35]:
# Create a dictionary with the counts
count_dict = {
    'Ease_of_Use': ease_of_use_count,
    'Usefulness': usefulness_count,
    'Intention_to_Use': intention_to_use_count
    
}

In [36]:
# Convert the dictionary to a DataFrame
count_df = pd.DataFrame(count_dict, index=[0])

# Display the count DataFrame
print(count_df)

   Ease_of_Use  Usefulness  Intention_to_Use
0      -362371     -389065           -466089

In [37]:
# Calculate the correlations
correlation_matrix = data[['Intention_to_Use', 'Ease_of_Use', 'Usefulness']].corr()

In [38]:
# Print the correlation matrix
print(correlation_matrix)

                  Intention_to_Use  Ease_of_Use  Usefulness
Intention_to_Use          1.000000     0.895901    0.914064
Ease_of_Use               0.895901     1.000000    0.922520
Usefulness                0.914064     0.922520    1.000000

In [39]:
import statsmodels.api as sm

In [40]:
# Define the dependent and independent variables
X = data[['Ease_of_Use', 'Usefulness']]
y = data['Intention_to_Use']

#y = data['Intention_to_Use_Indicator']

In [41]:
# Add a constant (intercept) to the independent variables
X = sm.add_constant(X)

In [42]:
# Fit a linear regression model
model = sm.OLS(y, X).fit()

In [43]:
# Print the regression summary
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:       Intention_to_Use   R-squared:                       0.854
Model:                            OLS   Adj. R-squared:                  0.854
Method:                 Least Squares   F-statistic:                 4.961e+06
Date:                Fri, 03 Nov 2023   Prob (F-statistic):               0.00
Time:                        22:16:55   Log-Likelihood:             5.8524e+05
No. Observations:             1694581   AIC:                        -1.170e+06
Df Residuals:                 1694578   BIC:                        -1.170e+06
Df Model:                           2
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
const          -0.0957      0.000   -664.937      0.000      -0.096      -0.095
Ease_of_Use     0.2933      0.001    465.031      0.000       0.292       0.295
Usefulness      0.5079      0.001    773.407      0.000       0.507       0.509
==============================================================================
Omnibus:                   822864.667   Durbin-Watson:                   1.978
Prob(Omnibus):                  0.000   Jarque-Bera (JB):          6061099.708
Skew:                          -2.229   Prob(JB):                         0.00
Kurtosis:                      11.122   Cond. No.                         7.37
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [44]:
# Save the updated dataset to a new CSV file
data.to_csv('fooddelivery_updated_sentiment2.csv', index=False)

In [45]:
len (data)

1694581